### ISSUE TITLE
yesboats command error

### ISSUE THREAD

**Issue by LeePC** [LearnerCouncil/YesBoats#11]
```[14:02:36] [Server thread/INFO]: Shinonono_Houki issued server command: /yesboats
[14:02:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'yesboats' in plugin Yesboats v1.5.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[banner-1.20.1-544-server.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[banner-1.20.1-544-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:882) ~[banner-1.20.1-544-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[banner-1.20.1-544-server.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:841) ~[brigadier-1.1.8.jar:?]
        at net.minecraft.commands.Commands.redirect$zbh000$architectury$performCommand(Commands.java:1545) ~[server-intermediary.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:287) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:3095) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:1321) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:67) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at rocks.learnercouncil.yesboats.commands.arguments.JoinArg.execute(JoinArg.java:26) ~[?:?]
        at rocks.learnercouncil.yesboats.commands.YesBoatsCmd.onCommand(YesBoatsCmd.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[banner-1.20.1-544-server.jar:?]
        ... 23 more

**To Reproduce**
Steps to reproduce the behavior:
1. /yesboats command error

**Minecraft version information**
- Minecraft Version: 1.20.1
 - Server Software: Banner
 - Server Software Version: Banner-604
 - Plugin Version : Latest Version

**Comment by H2ofiremaster** [comment]
Thank you for bringing this to my attention. This issue seems to be caused by the plugin not properly handling an incorrect use of the `/yesboats` command (i.e. running `/yesboats` standalone without further arguments). I'll be sure to fix this as soon as I can but in the meantime, you can run `/yesboats help`, or view the [README](https://github.com/LearnerCouncil/YesBoats/blob/main/README.md) to view the proper usage of the command.

Also, you seem to be running this plugin using [Banner](https://new.mohistmc.com/software/banner), which is not officially supported by the plugin. If it works, then that's great, but use it at your own risk.

**Comment by LeePC** [comment]
It's working well
